sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t complex/react-test -f ./client/Dockerfile.dev ./client
  # - docker build myOtherProject
script:
  #by default npm test enters watch mode(never going to exit)
  #add -- -- coverage to make sure that test script(npm test) exists with code 0(if tests run succesfully) or not 0(if tests are unsuccesfull)
  # - docker run complex/react-test npm test -- -- coverage
  #docker run myotherproject runmytests
  - docker run -e CI=true complex/react-test npm test
after_success:
  - docker build -t daniel1122z/multi-client ./client
  - docker build -t daniel1122z/multi-nginx ./nginx
  - docker build -t daniel1122z/multi-server ./server
  - docker build -t daniel1122z/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push daniel1122z/multi-client
  - docker push daniel1122z/multi-nginx
  - docker push daniel1122z/multi-server
  - docker push daniel1122z/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-471112974477"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"