sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t complex/react-test -f ./client/Dockerfile.dev ./client
  # - docker build myOtherProject
script:
  #by default npm test enters watch mode(never going to exit)
  #add -- -- coverage to make sure that test script(npm test) exists with code 0(if tests run succesfully) or not 0(if tests are unsuccesfull)
  # - docker run complex/react-test npm test -- -- coverage
  #docker run myotherproject runmytests
  - docker run -e CI=true complex/react-test npm test
after_success:
  - docker build -t complex/multi-client ./client
  - docker build -t complex/multi-nginx ./nginx
  - docker build -t complex/multi-server ./server
  - docker build -t complex/multi-worker ./worker